on: [push, pull_request]

name: CI

jobs:
  "Check_Website":
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Naev Website Repository
      uses: actions/checkout@v2

    - name: Update APT Cache
      run: |
        sudo apt-get update

    - name: Install Required APT Packages
      run: |
        sudo apt-get install \
          bundler \
          make \
          ruby-dev \
          tidy

    - name: Install Required Ruby Gems
      run: |
        bundle install

    - name: Compile Website
      run: |
        make

    - name: Upload Website Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: naev-${{ github.sha }}
        path: ${{ github.workspace }}/output/*
        if-no-files-found: error
